
    
    type SysProjectReady {
      createdAt:Date
      id:ID
      updatedAt:Date
      key:String
      mainMaterial:String
      auxiliaryMaterial:String
      deliveryCycle:String
      workerContact:String
      other:String
      
      
    }
    
    
    input WhereSysProjectReady_createdAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_id {
        op_eq: ID
  op_ne: ID
  op_or: [ID]
  op_gt: ID
  op_gte: ID
  op_lt: ID
  op_lte: ID
  op_between: [ID]
  op_notBetween: [ID]
  op_in: [ID]
  op_notIn: [ID]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_updatedAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_key {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_mainMaterial {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_auxiliaryMaterial {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_deliveryCycle {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_workerContact {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProjectReady_other {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      
    input WhereFieldSysProjectReady{
    createdAt:WhereSysProjectReady_createdAt
      id:WhereSysProjectReady_id
      updatedAt:WhereSysProjectReady_updatedAt
      key:WhereSysProjectReady_key
      mainMaterial:WhereSysProjectReady_mainMaterial
      auxiliaryMaterial:WhereSysProjectReady_auxiliaryMaterial
      deliveryCycle:WhereSysProjectReady_deliveryCycle
      workerContact:WhereSysProjectReady_workerContact
      other:WhereSysProjectReady_other
      
    }

    input WhereSysProjectReady {
      createdAt:WhereSysProjectReady_createdAt
      id:WhereSysProjectReady_id
      updatedAt:WhereSysProjectReady_updatedAt
      key:WhereSysProjectReady_key
      mainMaterial:WhereSysProjectReady_mainMaterial
      auxiliaryMaterial:WhereSysProjectReady_auxiliaryMaterial
      deliveryCycle:WhereSysProjectReady_deliveryCycle
      workerContact:WhereSysProjectReady_workerContact
      other:WhereSysProjectReady_other
      
      op_and: [WhereFieldSysProjectReady]
      op_or: [WhereFieldSysProjectReady]
      op_not: [WhereFieldSysProjectReady]
    }
    
    
    input AddSysProjectReady {
    key: String
      mainMaterial: String
      auxiliaryMaterial: String
      deliveryCycle: String
      workerContact: String
      other: String
      
    }
    
    
    input EditSysProjectReady {
    key: String
      mainMaterial: String
      auxiliaryMaterial: String
      deliveryCycle: String
      workerContact: String
      other: String
      
    }
    
    type CountSysProjectReady {
      count: Int
      rows: [SysProjectReady]
    }
    type ResDelSysProjectReady {
      count: Int
    }
    type ResEditSysProjectReady {
      ids: [Int]
    }
    