
    
    type CmsMaterialsTypes {
      createdAt:Date
      id:ID
      updatedAt:Date
      name:String
      
      cms_materials(order:[[String]],limit:Int,offset:Int): [CmsMaterials]

    }
    
    
    input WhereCmsMaterialsTypes_createdAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereCmsMaterialsTypes_id {
        op_eq: ID
  op_ne: ID
  op_or: [ID]
  op_gt: ID
  op_gte: ID
  op_lt: ID
  op_lte: ID
  op_between: [ID]
  op_notBetween: [ID]
  op_in: [ID]
  op_notIn: [ID]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereCmsMaterialsTypes_updatedAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereCmsMaterialsTypes_name {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      
    input WhereFieldCmsMaterialsTypes{
    createdAt:WhereCmsMaterialsTypes_createdAt
      id:WhereCmsMaterialsTypes_id
      updatedAt:WhereCmsMaterialsTypes_updatedAt
      name:WhereCmsMaterialsTypes_name
      
    }

    input WhereCmsMaterialsTypes {
      createdAt:WhereCmsMaterialsTypes_createdAt
      id:WhereCmsMaterialsTypes_id
      updatedAt:WhereCmsMaterialsTypes_updatedAt
      name:WhereCmsMaterialsTypes_name
      
      op_and: [WhereFieldCmsMaterialsTypes]
      op_or: [WhereFieldCmsMaterialsTypes]
      op_not: [WhereFieldCmsMaterialsTypes]
    }
    
    
    input AddCmsMaterialsTypes {
    name: String!
      
    }
    
    
    input EditCmsMaterialsTypes {
    name: String
      
    }
    
    type CountCmsMaterialsTypes {
      count: Int
      rows: [CmsMaterialsTypes]
    }
    type ResDelCmsMaterialsTypes {
      count: Int
    }
    type ResEditCmsMaterialsTypes {
      ids: [Int]
    }
    