
    
    type SysProvince {
      createdAt:Date
      id:ID
      updatedAt:Date
      name:String
      province_id:Int
      
      
    }
    
    
    input WhereSysProvince_createdAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProvince_id {
        op_eq: ID
  op_ne: ID
  op_or: [ID]
  op_gt: ID
  op_gte: ID
  op_lt: ID
  op_lte: ID
  op_between: [ID]
  op_notBetween: [ID]
  op_in: [ID]
  op_notIn: [ID]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProvince_updatedAt {
        op_eq: Date
  op_ne: Date
  op_or: [Date]
  op_gt: Date
  op_gte: Date
  op_lt: Date
  op_lte: Date
  op_between: [Date]
  op_notBetween: [Date]
  op_in: [Date]
  op_notIn: [Date]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProvince_name {
        op_eq: String
  op_ne: String
  op_or: [String]
  op_gt: String
  op_gte: String
  op_lt: String
  op_lte: String
  op_between: [String]
  op_notBetween: [String]
  op_in: [String]
  op_notIn: [String]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      input WhereSysProvince_province_id {
        op_eq: Int
  op_ne: Int
  op_or: [Int]
  op_gt: Int
  op_gte: Int
  op_lt: Int
  op_lte: Int
  op_between: [Int]
  op_notBetween: [Int]
  op_in: [Int]
  op_notIn: [Int]
  op_like: String
  op_notLike: String
  op_startsWith: String
  op_endsWith: String
  op_substring: String
      }
      
    input WhereFieldSysProvince{
    createdAt:WhereSysProvince_createdAt
      id:WhereSysProvince_id
      updatedAt:WhereSysProvince_updatedAt
      name:WhereSysProvince_name
      province_id:WhereSysProvince_province_id
      
    }

    input WhereSysProvince {
      createdAt:WhereSysProvince_createdAt
      id:WhereSysProvince_id
      updatedAt:WhereSysProvince_updatedAt
      name:WhereSysProvince_name
      province_id:WhereSysProvince_province_id
      
      op_and: [WhereFieldSysProvince]
      op_or: [WhereFieldSysProvince]
      op_not: [WhereFieldSysProvince]
    }
    
    
    input AddSysProvince {
    name: String!
      province_id: Int
      
    }
    
    
    input EditSysProvince {
    name: String
      province_id: Int
      
    }
    
    type CountSysProvince {
      count: Int
      rows: [SysProvince]
    }
    type ResDelSysProvince {
      count: Int
    }
    type ResEditSysProvince {
      ids: [Int]
    }
    